openapi: 3.0.0
info:
  title: UnderSounds API Authentication
  version: "1.0.0"
  description: "API para manejo de usuarios: registro, login, actualización, logout, OAuth2.0 con Google, recuperación de contraseña y refresh token mediante cookies."
servers:
  - url: http://localhost:5000/api

tags:
  - name: Authentication
    description: Endpoints de inicio/cierre de sesión y tokens.
  - name: Account
    description: Gestión y actualización de perfiles de usuario.
  - name: OAuth
    description: Flujo de autenticación externa (Google).
  - name: PasswordRecovery
    description: Solicitud y restablecimiento de contraseña (OTP).

paths:
  /auth/register:
    post:
      tags: [Authentication]
      summary: Registra una nueva cuenta.
      requestBody:
        description: Datos del usuario a crear.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: fanUser1
                email:
                  type: string
                  example: fan1@example.com
                password:
                  type: string
                  example: password123
              required:
                - username
                - email
                - password
      responses:
        "201":
          description: Cuenta creada exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "500":
          description: Error interno.
  /auth/login:
    post:
      tags: [Authentication]
      summary: Inicia sesión.
      requestBody:
        description: Credenciales para acceder.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: fan1@example.com
                password:
                  type: string
                  example: password123
              required:
                - email
                - password
      responses:
        "200":
          description: Login exitoso. Devuelve el access token en el body y setea el refresh token en cookie HttpOnly.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "401":
          description: Credenciales inválidas.
  /auth/refresh-token:
    post:
      tags: [Authentication]
      summary: Refresca el access token usando el refresh token almacenado en cookie.
      responses:
        "200":
          description: Nuevo access token generado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: newAccessToken123
        "401":
          description: Refresh token inválido o caducado.
  /auth/{id}:
    put:
      tags: [Account]
      summary: Actualiza el perfil de un usuario.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        description: Campos a actualizar.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: nuevoNombre
                bio:
                  type: string
                  example: Nueva bio
                bandName:
                  type: string
                  example: The Rockers
                genre:
                  type: string
                  example: Rock
                labelName:
                  type: string
                  example: Super Records
                website:
                  type: string
                  example: https://ejemplo.com
      responses:
        "200":
          description: Cuenta actualizada.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        "500":
          description: Error interno.
  /auth/logout:
    post:
      tags: [Authentication]
      summary: Cierra la sesión del usuario.
      responses:
        "200":
          description: Logout exitoso. Se borra el access token en memoria y se elimina la cookie del refresh token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
  /auth/forgot-password:
    post:
      tags: [PasswordRecovery]
      summary: Solicita recuperación de contraseña.
      requestBody:
        description: Email del usuario para enviar el código OTP.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: fan1@example.com
      responses:
        "200":
          description: Mensaje de confirmación (el código se envía si la cuenta existe).
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Si el correo existe, se enviará un código de recuperación."
        "500":
          description: Error interno.
  /auth/reset-password:
    post:
      tags: [PasswordRecovery]
      summary: Restablece la contraseña utilizando el código OTP.
      requestBody:
        description: Email, código OTP y la nueva contraseña.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: fan1@example.com
                otp:
                  type: string
                  example: "AbC123"
                newPassword:
                  type: string
                  example: newPassword123
      responses:
        "200":
          description: Contraseña actualizada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        "400":
          description: Código OTP inválido o caducado.
        "500":
          description: Error interno.
  /auth/google:
    get:
      tags: [OAuth]
      summary: Inicia autenticación con Google.
      responses:
        "302":
          description: Redirige a Google para autenticación.
  /auth/google/callback:
    get:
      tags: [OAuth]
      summary: Callback de autenticación con Google.
      responses:
        "302":
          description: Redirige al frontend tras autenticación exitosa.
           
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
          example: 60d0fe4f5311236168a109ca
        username:
          type: string
          example: fanUser1
        email:
          type: string
          example: fan1@example.com
        role:
          type: string
          example: fan
        profileImage:
          type: string
          example: /assets/images/default-user.jpg
        bio:
          type: string
          example: Soy un fanático de la música.
        bandName:
          type: string
          example: The Rockers
        genre:
          type: string
          example: Rock
        labelName:
          type: string
          example: Super Records
        website:
          type: string
          example: https://www.therockers.com